### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by LaskoA**
Please check it, thank you :)

### CODE REVIEW

**Review by Abnormaltype — CHANGES_REQUESTED** [review]
Also, add more tests

**Comment by LaskoA** [comment]
Please check after names were changed.

**Review by Abnormaltype — CHANGES_REQUESTED** [review]
okay, but add tests when is large human age, or zero, or mb negative

**Comment by LaskoA** [comment]
3 tests were added (huge value, negative value and zero value). Thank you :)

**Review by Abnormaltype — APPROVED** [review]
Good job!)

**Pull request closed without merging**
